[package]

name = "web-rockets"
version = "0.0.1"
authors = [ "Your name <you@example.com>" ]

[dependencies]
mio = "0.4.4"
rust-crypto = "0.2.34"
rustc-serialize = "0.3.16"

[[bin]]

name = "hello_world"